### ISSUE TITLE
[meta] RSVP functionality

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#104]
Users should be able to RSVP via:

- [ ] reply to SMS when they get a message about an upcoming game
- [ ] Reply to email reminder about upcoming game
- [ ] visit the website, go to a page, click an RSVP button

RSVP statuses:

- yes
- no
- maybe
